Repository sixcodes/python-boilerplate, pull requests merged in 2020-12, with the labels that each got.

#41 Adicionando a primeira parte de varios checks
  .bandit
  .flake8
  .gitignore
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  README.md
  docs-src/conf.py
  myproj/config.py
  mypy.ini
  pyproject.toml
  setup.cfg
  setup.py
  tests/test_config.py
  tests/test_true.py
Labels: enhancement, feature

#43 Roolback do workflow do release draft
  .github/workflows/release-drafter.yaml
Labels: bug, docs, enhancement

#51 Remove a pasta docs/ e documenta a config do sphinx
  README.md
  {{cookiecutter.project_name}}/docs/.buildinfo
  {{cookiecutter.project_name}}/docs/.doctrees/environment.pickle
  {{cookiecutter.project_name}}/docs/.doctrees/index.doctree
  {{cookiecutter.project_name}}/docs/_sources/index.rst.txt
  {{cookiecutter.project_name}}/docs/_static/_stemmer.js
  {{cookiecutter.project_name}}/docs/_static/alabaster.css
  {{cookiecutter.project_name}}/docs/_static/basic.css
  {{cookiecutter.project_name}}/docs/_static/custom.css
  {{cookiecutter.project_name}}/docs/_static/doctools.js
  {{cookiecutter.project_name}}/docs/_static/documentation_options.js
  {{cookiecutter.project_name}}/docs/_static/file.png
  {{cookiecutter.project_name}}/docs/_static/jquery-3.5.1.js
  {{cookiecutter.project_name}}/docs/_static/jquery.js
  {{cookiecutter.project_name}}/docs/_static/language_data.js
  {{cookiecutter.project_name}}/docs/_static/minus.png
  {{cookiecutter.project_name}}/docs/_static/plus.png
  {{cookiecutter.project_name}}/docs/_static/pygments.css
  {{cookiecutter.project_name}}/docs/_static/searchtools.js
  {{cookiecutter.project_name}}/docs/_static/translations.js
  {{cookiecutter.project_name}}/docs/_static/underscore-1.3.1.js
  {{cookiecutter.project_name}}/docs/_static/underscore.js
  {{cookiecutter.project_name}}/docs/genindex.html
  {{cookiecutter.project_name}}/docs/index.html
  {{cookiecutter.project_name}}/docs/objects.inv
  {{cookiecutter.project_name}}/docs/search.html
  {{cookiecutter.project_name}}/docs/searchindex.js
Labels: bug, docs

#49 Criando um workflow para release no Pypi
  README.md
  cookiecutter.json
  {{cookiecutter.project_name}}/.github/workflows/pull-request.yaml
  {{cookiecutter.project_name}}/.github/workflows/release-drafter.yaml
  {{cookiecutter.project_name}}/.github/workflows/release.yaml
  {{cookiecutter.project_name}}/docs/.buildinfo
  {{cookiecutter.project_name}}/docs/.doctrees/environment.pickle
  {{cookiecutter.project_name}}/docs/.doctrees/index.doctree
  {{cookiecutter.project_name}}/docs/_sources/index.rst.txt
  {{cookiecutter.project_name}}/docs/_static/_stemmer.js
  {{cookiecutter.project_name}}/docs/_static/alabaster.css
  {{cookiecutter.project_name}}/docs/_static/basic.css
  {{cookiecutter.project_name}}/docs/_static/custom.css
  {{cookiecutter.project_name}}/docs/_static/doctools.js
  {{cookiecutter.project_name}}/docs/_static/documentation_options.js
  {{cookiecutter.project_name}}/docs/_static/file.png
  {{cookiecutter.project_name}}/docs/_static/jquery-3.5.1.js
  {{cookiecutter.project_name}}/docs/_static/jquery.js
  {{cookiecutter.project_name}}/docs/_static/language_data.js
  {{cookiecutter.project_name}}/docs/_static/minus.png
  {{cookiecutter.project_name}}/docs/_static/plus.png
  {{cookiecutter.project_name}}/docs/_static/pygments.css
  {{cookiecutter.project_name}}/docs/_static/searchtools.js
  {{cookiecutter.project_name}}/docs/_static/translations.js
  {{cookiecutter.project_name}}/docs/_static/underscore-1.3.1.js
  {{cookiecutter.project_name}}/docs/_static/underscore.js
  {{cookiecutter.project_name}}/docs/genindex.html
  {{cookiecutter.project_name}}/docs/index.html
  {{cookiecutter.project_name}}/docs/objects.inv
  {{cookiecutter.project_name}}/docs/search.html
  {{cookiecutter.project_name}}/docs/searchindex.js
Labels: feature

#53 AJustando para fazer relase no pypi quando fechar uma release pelo gi…
  {{cookiecutter.project_name}}/.github/workflows/release.yaml
  {{cookiecutter.project_name}}/setup.py
Labels: bug
